### ISSUE TITLE
Request to Translate README to English

### ISSUE THREAD

**Issue by sabirnc** [ThomRib/Si-Hemat#98]
Hello, I came across your financial management repository and am interested in contributing to this project. However, I noticed that the README file is written in a foreign language, making it difficult for non-native speakers to understand the project’s purpose, setup instructions, and contribution guidelines.

Could the README be translated into English? This would help attract more contributors from diverse backgrounds and enhance the project's accessibility.

Thank you for considering this request, and I look forward to contributing!

Best regards,
sabir

**Comment by ThomRib** [comment]
Thenks for advice, 
I will try to make it into English

**Comment by sabirnc** [comment]
You're welcome! Glad I could help.

**Comment by sabirnc** [comment]
we can close this issue  once new Readme in English available
